Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [15]:
import numpy as np
import matplotlib.pyplot as plt


n = 10
numpy_array = np.arange(n-1, -1, -1)
print(numpy_array)


[9 8 7 6 5 4 3 2 1 0]


Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [29]:
n = 3
numpy_matrix = np.diag(np.arange(n, -1, -1))
print(numpy_matrix, '\n Сумма диагонали - ', np.trace(numpy_matrix))

[[3 0 0 0]
 [0 2 0 0]
 [0 0 1 0]
 [0 0 0 0]] 
 Сумма диагонали -  6


Задание 3
Решите систему уравнений:

4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [8]:
a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b = np.array([4, 12, -3])
result = np.linalg.solve(a, b)
print(result, np.dot(a, result))


[ 0.46666667  3.84444444 -5.55555556] [ 4. 12. -3.]


Задача 4 домашнего задания
Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:
На сайт заходит очередной посетитель, о покупках которого известно следующее:
Найдите самого похожего пользователя. Т. е. посчитайте косинусное расстояние между этим пользователем и всеми пользователями из массива user_stats

In [55]:
def cosine(a, b):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )


users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
)

next_user_stats = np.array([0, 1, 2, 0, 0, 0])
cos_list = []

for user in users_stats:
    cos_list.append(cosine(next_user_stats, user))

similar_to = users_stats[cos_list.index(max(cos_list))]

print(f'Ближайшее значение к искомому {next_user_stats} это {similar_to}')

Ближайшее значение к искомому [0 1 2 0 0 0] это [0 1 1 0 0 0]
